- link:
    ~/.config/BetterDiscord:
      path: /home/itsco/Dotfiles/Config/BetterDiscord
      create: true
      relink: true
      force: false
    ~/.config/gtk-3.0:
      path: /home/itsco/Dotfiles/Config/gtk-3.0
      create: true
      relink: true
      force: false
    ~/.gtkrc-2.0:
      path: /home/itsco/Dotfiles/Config/gtkrc-2.0
      create: true
      relink: true
      force: false
    ~/.zshrc:
      path: /home/itsco/Dotfiles/Config/zshrc
      create: true
      relink: true
      force: false
    ~/.config/alacritty:
      path: /home/itsco/Dotfiles/Config/alacritty
      create: true
      relink: true
      force: false
    ~/.config/awesome:
      path: /home/itsco/Dotfiles/Config/awesome-elenapan
      create: true
      relink: true
      force: false
    ~/.config/spicetify:
      path: /home/itsco/Dotfiles/Config/spicetify
      create: true
      relink: true
      force: false
    ~/.config/wpg:
      path: /home/itsco/Dotfiles/Config/wpg
      create: true
      relink: true
      force: false
    ~/.config/OpenRGB:
      path: /home/itsco/Dotfiles/Config/OpenRGB
      create: true
      relink: true
      force: false